################# Plugins ##################
plugins:
   - rubocop-performance
   - rubocop-rails
################# Bundler ##################

################# Gemspec ##################

################# Layout ###################

################# Lint #####################

################# Metrics ##################

################# Migration ################

################# Naming ###################

################# Performance ##############

################# Rails ####################

################# Security #################

################# Style ####################
